export const authConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const verifyConstant = {
  CODE_REQUEST: "CODE_REQUEST",
  CODE_SUCCESS: "CODE_SUCCESS",
  CODE_FAILURE: "CODE_FAILURE",
  VERIFY_REQUEST: "VERIFY_REQUEST",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",
  VERIFY_FAILURE: "VERIFY_FAILURE",
};

export const orderConstant = {
  ORDER_PLACE_REQUEST: "ORDER_PLACE_REQUEST",
  ORDER_PLACE_SUCCESS: "ORDER_PLACE_SUCCESS",
  ORDER_PLACE_FAILURE: "ORDER_PLACE_FAILURE",
  ORDER_GET_REQUEST: "ORDER_GET_REQUEST",
  ORDER_GET_SUCCESS: "ORDER_GET_SUCCESS",
  ORDER_GET_FAILURE: "ORDER_GET_FAILURE",
};

export const vendorConstant = {
  VENDOR_GET_REQUEST: "VENDOR_GET_REQUEST",
  VENDOR_GET_SUCCESS: "VENDOR_GET_SUCCESS",
  VENDOR_GET_FAILURE: "VENDOR_GET_FAILURE",
};
